language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: E0qLbBTRbw1uQDvm2s4YceG/0Vn/7OiuRqvWgkP4FIk++B8XYak11VssD/aD9dO12cuHzRiOP3uQ4MMOqZ0MSWpKvLTnmvuPsabpL0gP/R6lYoTdNiGfNxNbp98kdxFDyu8Mk1ScJ0M/xi9mgNn8EIkBULpTMu+1/PrLpJyN3LkEEQCMeqgTdSX3EivGp16yMSHSYaZ3ca848eJFfxXBrmfD32N1QV33MJpw1VKFP4zwCzq4gpdcedtMcwoMjEccTNH53hfhRqz54Lto+FPslcVS4w1RL03txLUKnkZyPj48oYb7TD6UDWFLCN5mEq10sBMAwbQIP6KuywOFzXkDhqSHTksnJbXwVgQXP9yjdzLpYaUawx0FokxvvhEjDzBZ1YYEfk4DvB9ynrJ5ZavbDRce1pcXkm19J76TnL62vnRuKosKejk0pgTerCCRnxlPozxv5BgWLc0ZU+ixNXpw9If/bsxc0O8f4RhdEzsZ0Aa0/URbPx2FQHAJSV2+1eNJ2/GdbADihWX4VOAGWDhg9kLaqe1ZCwGqrGskhK0xT0QfApcmAwJSDU1QANZ6Dx1y4BWfnqQk+XhoLLxdnn4QNkW8TEYi5M9RRNVlSUxNM8tKShU6j+OSWOc7kJo2oCQBDumhH4N5RIYHE5bvMSth9zR+sI/jFmrQ+x1VsuYPAbQ=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
