language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- oldrel
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: QxCwkVen5rM87LwZs/E8GoxVeMUefwynEKt8IBkgYBjJzXLidNVS5p+YzBrrIDsOTDt2ROB4C6fjtxRHwpmLjKLlWjLMcCHkKHpgnpvwX1hLcXpIbElC+6jnn5+Am06m2Xauqo9YFh3Ld4Kgo3LCQqI5NvwpH7+wKA3UzNdEzVubFrAYzt4hZYefnDmyaauI+9ZjxKcK2VLCfMSt8qkVIrCMoz3iou5WUHhlIO7GLECOr2xUKVudqwRNDZZvTIwNZd64TqOTk7dKYvDAnnLN/utE1XZn3nSy8jq2V76p40mlKTmu7WDuwg2jMWZn6wS0e5f3WwTnYeiLwW7HZhAekc9T2R9askr2RKrGcxQWOrscSBZntRoM81jF8iVejqvIWQNuvues6U1S6IddelHTYFjX7MABhQ993pEREzmcuEfFdSxfgB/eYk928aC0+a0/l2vUhKEd4FzQFMsII5bokwo5x1+AC87ezCh2PZmbdA0A/fPTzO4yt2/sFGqQu7a5FbwoziItZUZmCdDsX8sKdTzCe/V9vROoJNNR8zeWgQddhBvmVsgeFm0h3n6ozBcM6Vd7sBmG5mjGKAEV65mSZYxfnB+VlQ5nsJtZOD0PxLb00QgAyV0FYXKHRczPBok15xm2OkGmicjgIy0ew9BmlpQ+PQ7JSjbg4I5yHagTG1k=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
