language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: IeMEscIgAX5eVvYfEx2G8L0DMqrf52Rqx23qj7Jqxb86aYSKzQgINMGB7UO5lMIHu5W9GOyaFYBEO9dmG0fqZuSxn5nCGhXlCBaiHP+1/cX7eqIPW7TfROzGGB6KfjmhEmPqp2558tlNtsJjOaMM6fubm6RnRkSB0QX7DsXQ3kPGi3XejkV/bYGZhkSyvUMtW76s3Hn1oBpP8tgKBf7190ZYKw3zbQu7yv2GGPXoGsk7quoE/HDQY9DTisMdaiaam5bK9bF5/uJ8VGjPdrKn3UsmvfvwFarpnxn50+IiLtRDbilpHYG/FYcQ/yVYplxfSzRIU1gzwaeZMq4pHnRPR5u9m4aaEJlD0BS2CXeo3P5QAOKOjeqg6AZPBIwwI6e4vbOJK4C8Iaen/a/YPp4tMPQ0QkBvlabWoSy3nqAt+/F7DBCXjs+5WfmPTLW/euH5zWF5Qw4yBMHQfs59Z4DOxXpXg5m93qas53bFOazKIJuB6ESJTqFMc4Hpw/4wcmTEcnRmhuCQ8lFZwohRKrXFqMRgABaEsmFtaLHrKDmpkBRHA1CJQLKCHagEm/kMA+1e3HYuKP/cD7V+ecCuuTrcbPpDiFgNQVW24wAbFlP1xOjPAf1slU6Ibi8Ho+ch5Uji1fxnRDbGqLd/vwlB7XKZD2YTFfK6D/T02F7lhNOlyls=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then travis_wait 100 Rscript -e 'covr::coveralls(type
  = "all")' ; fi
